app:
  name: wlkg
  endpoint: https://kgccc.di.unito.it/sparql/wl-kg
  namespace: 
    left:
      entitytype1: 
        type: prov:Person 
        prefix: "PREFIX prov: <http://www.w3.org/ns/prov#>"
    right:
      entità1:
        label: book
        rel: urw:wasAttributedTo
      entità2:
        label: publisher
        rel: urw:wasPublishedBy
      entità3:
        label: language
        rel: urw:publishingLanguage
      entità4:
        label: wasPublishedWhen
        rel: urw:wasPublishedWhen
  prefix: 
    urw: <https://purl.archive.org/urwriters#> 
  prefixes: |
    urw: <https://purl.archive.org/urwriters#> 
    rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    prov: <http://www.w3.org/ns/prov#>
    urb: <https://purl.archive.org/urbooks#>
  template: 
    QuestionFocus: ''
    entities:
      work: []
      person: [] 
      subject: []
      publisher: []