app:
  name: wlkg
  endpoint: https://fuseki.hfpo-kfpo.di.unito.it/wlkg/query
  namespace: 
    left:
      entitytype1: 
        type: prov:Person 
        prefix: "PREFIX prov: <http://www.w3.org/ns/prov#>"
    right:
      entità1:
        label: book
        rel: urw:wasAttributedTo
      entità2:
        label: publisher
        rel: urw:wasPublishedBy
      entità3:
        label: language
        rel: urw:publishingLanguage
      entità4:
        label: wasPublishedWhen
        rel: urw:wasPublishedWhen
  prefix: 
    urw: <https://purl.archive.org/urwriters#> 
  prefixes: |
    PREFIX urw: <http://purl.archive.org/urwriters#> 
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX urb: <http://purl.archive.org/urbooks#>
  template: 
    QuestionFocus: ''
    entities:
      work: []
      person: [] 
      subject: []
      publisher: []
  properties:
    - prov:wasAttributedTo : wrote
    - urw:wasPublishedBy : has publisher
    - urw:publishingLanguage : published in
    - urw:citizenship: citizen of
    - urw:yearOfBirth: birth year
    - urw:countryOfBirth: country of birth
    - urw:authorTopic: has topic
  files:
    work: data/faiss_db/text/work.faiss
    person: data/faiss_db/text/person.faiss
    subject: data/faiss_db/text/subject.faiss
    publisher: data/faiss_db/text/publisher.faiss
