app:
  name: wlkg
  endpoint: https://kgccc.di.unito.it/sparql/wl-kg
  namespace: 
    left:
      entitytype: urw:Person 
    right:
      entità1:
        label: book
        rel: urw:wasAttributedTo
      entità2:
        label: publisher
        rel: urw:wasPublishedBy
      entità3:
        label: language
        rel: urw:publishingLanguage
      entità4:
        label: wasPublishedWhen
        rel: urw:wasPublishedWhen
  prefix: 
    urw: <https://purl.archive.org/urwriters#> 
